### ISSUE TITLE
XADD compilation fails for Elevators instances with a single elevator object

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [pyrddlgym-project/pyRDDLGym-symbolic#6]
Hi, for the [Elevators](https://github.com/pyrddlgym-project/rddlrepository/blob/main/rddlrepository/archive/competitions/IPPC2014/Elevators/MDP/domain.rddl) domain and [instance_1](https://github.com/pyrddlgym-project/rddlrepository/blob/main/rddlrepository/archive/competitions/IPPC2014/Elevators/MDP/instance1.rddl) I get the following error message when I try to instantiate the class `RDDL2Graph`:

```
RDDLInvalidNumberOfArgumentsError: Logical operator | does not have the required number of args, got 1
Expression(etype=('boolean', '|'), args=
    Expression(etype=('boolean', '^'), args=
        Expression(etype=('boolean', '^'), args=
            Expression(etype=('pvar', 'elevator-at-floor___e0__f0'), args=('elevator-at-floor___e0__f0', None))
            Expression(etype=('boolean', '~'), args=
                Expression(etype=('pvar', 'elevator-dir-up___e0'), args=('elevator-dir-up___e0', None))))
        Expression(etype=('boolean', '~'), args=
            Expression(etype=('pvar', 'elevator-closed___e0'), args=('elevator-closed___e0', None)))))
```

However, it works without any problems for every Elevators instance with more than one `elevator` object.

**Comment by jihwan-jeong** [comment]
Hi @GMMDMDIDEMS, thank you for reporting the error!

The error is due to the fact that `exists_{?e: elevator} []` is converted to a series of `|` operations, but if there's only a single object, the `len(args)==1`, and the previous code didn't handle this case with the `or` operation. bb59bdf27 should have fixed this issue and you can properly compile the domain now.

Also, I suggest updating both `pyrddlgym-symbolic` and the `xaddpy` packages directly through pip to use the updated code.

Let me know if things don't work out as intended!

**Comment by GMMDMDIDEMS** [comment]
Thanks for the quick fix and for updating the packages.
